# Generated by Django 5.2.12 on 2026-03-19 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('matched_required_skills', models.JSONField(default=list)),
                ('missing_required_skills', models.JSONField(default=list)),
                ('explanation', models.JSONField(default=dict)),
                ('algorithm_version', models.CharField(default='v1_rule_based', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seeker_id', 'job_id'], name='matching_ma_seeker__6027a2_idx')],
            },
        ),
    ]
