# Generated by Django 5.2.12 on 2026-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_id', models.UUIDField(db_index=True)),
                ('job_id', models.IntegerField(db_index=True)),
                ('required_skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rule_based_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('semantic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_required_skills', models.JSONField(default=list)),
                ('missing_required_skills', models.JSONField(default=list)),
                ('explanation', models.JSONField(default=dict)),
                ('algorithm_version', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['seeker_id', 'job_id', 'algorithm_version'], name='matching_ma_seeker__960199_idx')],
            },
        ),
    ]
