# Generated by Django 5.2.12 on 2026-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='job_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
