# Generated by Django 5.2.12 on 2026-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_matchresult_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
