# Generated by Django 5.2.12 on 2026-03-19 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matchresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
