services:
  # FRONTEND - React
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api/
        VITE_WEBSOCKET_URL: ws://192.168.56.14/ws/chat/
    ports:
      - "80:80"
    volumes:
      - static_data:/usr/share/nginx/html/static
      - media_data:/usr/share/nginx/html/media 
    depends_on:
      - auth-service
      - company-service
      - seeker-service
      - chat-service

  # AUTH SERVICE - WSGI
  auth-service:
    build:
      context: ./auth-service
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DATABASE_URL=${AUTH_SERVICE_DB_URL}
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,192.168.56.14
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://192.168.56.14
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASS}
    volumes:
      - auth_data:/var/lib/postgresql/data

  # COMPANY SERVICE - WSGI
  company-service:
    build:
      context: ./company-service
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DATABASE_URL=${COMPANY_SERVICE_DB_URL}
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,192.168.56.14
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://192.168.56.14
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media 
    depends_on:
      - company-db

  company-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${COMPANY_SERVICE_DB_NAME}
      POSTGRES_USER: ${COMPANY_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${COMPANY_SERVICE_DB_PASS}
    volumes:
      - company_data:/var/lib/postgresql/data

  # SEEKER SERVICE - WSGI
  seeker-service:
    build:
      context: ./seeker-service
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DATABASE_URL=${SEEKER_SERVICE_DB_URL}
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,192.168.56.14
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://192.168.56.14
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      - seeker-db

  seeker-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${SEEKER_SERVICE_DB_NAME}
      POSTGRES_USER: ${SEEKER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${SEEKER_SERVICE_DB_PASS}
    volumes:
      - seeker_data:/var/lib/postgresql/data

  # CHAT SERVICE - ASGI
  chat-service:
    build:
      context: ./chat-service
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DATABASE_URL=${CHAT_SERVICE_DB_URL}
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,192.168.56.14
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://192.168.56.14
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      - chat-db
      - redis

  chat-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${CHAT_SERVICE_DB_NAME}
      POSTGRES_USER: ${CHAT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${CHAT_SERVICE_DB_PASS}
    volumes:
      - chat_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  auth_data:
  company_data:
  seeker_data:
  chat_data:
  static_data:
  media_data:
