# Generated by Django 5.2.12 on 2026-03-23 11:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.IntegerField(db_index=True, unique=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('normalized_text', models.TextField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_matchable', models.BooleanField(default=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('embedding_text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedding_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeekerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker_id', models.UUIDField(db_index=True, unique=True)),
                ('skills', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('total_experience_years', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('normalized_text', models.TextField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_matchable', models.BooleanField(default=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('embedding_text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedding_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
