# Generated by Django 5.2.12 on 2026-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsnapshot',
            name='job_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
