# Generated by Django 5.2.12 on 2026-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='raw_payload',
        ),
    ]
