# Generated by Django 5.2.12 on 2026-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_alter_jobsnapshot_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='preferred_skills',
        ),
    ]
