# Generated by Django 5.2.12 on 2026-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_remove_jobsnapshot_raw_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='embedding_generated_at',
        ),
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='jobsnapshot',
            name='embedding_text_hash',
        ),
    ]
