# Generated by Django 5.2.12 on 2026-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_remove_jobsnapshot_preferred_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekersnapshot',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='jobsnapshot',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seekersnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seekersnapshot',
            name='total_experience_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
