# Generated by Django 5.2.12 on 2026-03-23 11:28

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_remove_jobsnapshot_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsnapshot',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='jobsnapshot',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsnapshot',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobsnapshot',
            name='embedding_text_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobsnapshot',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
    ]
