# Generated by Django 5.0.7 on 2024-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company', 'Company'), ('admin', 'Admin')], default='job_seeker', max_length=20, null=True),
        ),
    ]
