# Generated by Django 5.1 on 2025-11-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("company", "Company"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
