# Generated by Django 5.0.7 on 2024-08-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company', 'Company'), ('admin', 'Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
