# Generated by Django 5.1 on 2026-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_company_user_company_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="employment_type",
        ),
        migrations.RemoveField(
            model_name="job",
            name="last_date_to_apply",
        ),
        migrations.RemoveField(
            model_name="job",
            name="vacancy",
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.CharField(
                default=1,
                help_text="Comma-separated list of required skills",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
