# Generated by Django 5.1 on 2026-03-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_job_employment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
