# Generated by Django 5.1 on 2026-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_job_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
