# Generated by Django 5.1 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
