# Generated by Django 5.0.7 on 2024-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile pictures/'),
        ),
    ]
