# Generated by Django 5.1 on 2025-11-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seekerprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="user_id",
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="seekerprofile",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="seekerprofile",
            name="profile_photo",
            field=models.ImageField(null=True, upload_to="profile pictures/"),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seeker.seekerprofile",
                    ),
                ),
            ],
        ),
    ]
