# Generated by Django 5.1 on 2026-03-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker", "0003_education_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_year",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_year",
            field=models.CharField(max_length=150),
        ),
    ]
