# Generated by Django 5.1 on 2026-03-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker", "0004_alter_education_end_year_alter_education_start_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
