# Generated by Django 5.0.7 on 2025-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_rename_user_experience_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='user_id',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
