# Generated by Django 5.1 on 2026-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeker", "0005_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
