# Generated by Django 5.1 on 2025-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.AddField(
            model_name="message",
            name="room_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
