# Generated by Django 5.1 on 2026-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_room_message_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
